include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false

  # Ce détermine la rigueur de Flutter lorsqu'il analyse votre code
  # Aussi on peut augmenter la rigueur de l'analyseur à mesure que vous approcherez de la publication de la véritable application de production